### ISSUE TITLE
Inconsistent hashes in different scenarios

### ISSUE THREAD

**Issue by yoshuawuyts** [mafintosh/siphash24#3]
It seems that running `siphash24` on different OS'es / Node versions can yield different results. This might be because of what we're doing, but given that the output files have been fingerprinted and consistent between versions it seems it might actually be the hashing algo.

The best repro we got at the moment is the Bankai test suite of the [new-new-new branch](https://github.com/choojs/bankai/pull/241). It yields different hashes between Node 4, and Node 6 and Node 8 ([link to Travis](https://travis-ci.org/choojs/bankai/)).

I'm not sure what's going on, but further investigation would probably be good. Thanks!

## Refs
- https://github.com/choojs/bankai/pull/241#issuecomment-331282918
- https://github.com/choojs/bankai/pull/241#issuecomment-331525182
- https://travis-ci.org/choojs/bankai/

**Comment by yoshuawuyts** [comment]
It's definitely us :(

**Comment by mafintosh** [comment]
oh bummer, do you have more details? curious

**Comment by yoshuawuyts** [comment]
Haha, it's looking like I have some race condition in Bankai when creating `bundle.js`. I think node 4 was just slow enough that we'd consistently hit it. Digging in further to figure out what's up on our end (:
